# Generated by Django 3.2.15 on 2022-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(default='', upload_to='face/images/'),
        ),
    ]
